; 场景 · 🎬 海外音影社
; Netflix / Spotify / Reddit / Discord / 巴哈姆特 / EMBY / TikTok 等

; 主流流媒体与社区平台
ruleset=场景 · 🎬 海外音影社,[]GEOSITE,netflix
ruleset=场景 · 🎬 海外音影社,[]GEOSITE,disney
ruleset=场景 · 🎬 海外音影社,[]GEOSITE,hulu
ruleset=场景 · 🎬 海外音影社,[]GEOSITE,primevideo
ruleset=场景 · 🎬 海外音影社,[]GEOSITE,hbo
ruleset=场景 · 🎬 海外音影社,[]GEOSITE,spotify
ruleset=场景 · 🎬 海外音影社,[]GEOSITE,twitch
ruleset=场景 · 🎬 海外音影社,[]GEOSITE,pixiv
ruleset=场景 · 🎬 海外音影社,[]GEOSITE,reddit
ruleset=场景 · 🎬 海外音影社,[]GEOSITE,discord
ruleset=场景 · 🎬 海外音影社,[]GEOSITE,twitter

; 巴哈姆特（台湾动画平台）
ruleset=场景 · 🎬 海外音影社,[]DOMAIN-SUFFIX,gamer.com.tw
ruleset=场景 · 🎬 海外音影社,[]DOMAIN-SUFFIX,bahamut.com.tw

; EMBY 影视服务器
ruleset=场景 · 🎬 海外音影社,[]DOMAIN-SUFFIX,emby.wtf
ruleset=场景 · 🎬 海外音影社,[]DOMAIN-SUFFIX,emby.nz

; TikTok
ruleset=场景 · 📱 TikTok,[]GEOSITE,tiktok
